import Footer from '@/components/layout/Footer'
import Navbar from '@/components/layout/Navbar'
import { ApiProvider } from '@/lib/api/apiClient'
import { authOptions } from '@/lib/auth'
import ClientProvider from '@/providers/ClientProvider'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { Montserrat, Roboto } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin', 'cyrillic'],
})

const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'Beauty House Professional',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const session = await getServerSession(authOptions)

	return (
		<html lang='en'>
			<body className={`${montserrat.variable} ${roboto.variable} antialiased`}>
				<ClientProvider session={session}>
					<ApiProvider />
					<Toaster position='top-center' />
					<Navbar />
					<main>{children}</main>
					<Footer />
				</ClientProvider>
			</body>
		</html>
	)
}
